Null Error Fix
MissingReferenceException: The object of type 'UnityEngine.Transform' has been destroyed but you are still trying to access it. Your script should either check if it is null or you should not destroy the object. UnityEngine.Object+MarshalledUnityObject.TryThrowEditorNullExceptionObject (UnityEngine.Object unityObj, System.String parameterName) (at <b5bf0c891ea345fe93688f835df32fdc>:0) UnityEngine.Bindings.ThrowHelper.ThrowNullReferenceException (System.Object obj) (at <b5bf0c891ea345fe93688f835df32fdc>:0) UnityEngine.Transform.get_position () (at <b5bf0c891ea345fe93688f835df32fdc>:0) EnemyPatrol.PlayerInSight () (at Assets/Enemy/EnemyPatrol.cs:161) EnemyPatrol.PatrolUpdate () (at Assets/Enemy/EnemyPatrol.cs:52) EnemyPatrol.Update () (at Assets/Enemy/EnemyPatrol.cs:44)

the above error appears when i killed off the enemy.

Solution:

 private bool PlayerInSight()
 {
     if (Player == null) return false;
     if (!enemy) return false;

     float distanceToPlayer = Vector2.Distance(enemy.position, Player.position);
     bool inRange = Mathf.Abs(Player.position.x - enemy.position.x) <= chaseRange;
     return inRange && distanceToPlayer <= maxchaseRange;
 }

include:         if (!enemy) return false;