Boss Enemy Design
Projectile: No ProjectillePickup found on this projectile or its parent/children!
UnityEngine.Debug:LogError (object)
Projectile:OnEnable () (at Assets/Player/Projectiles/Projectile.cs:88)
UnityEngine.Object:Instantiate<Projectile> (Projectile)
PlayerShoot:Shoot () (at Assets/Player/PlayerShoot.cs:57)
PlayerShoot:Update () (at Assets/Player/PlayerShoot.cs:33)

NullReferenceException: Object reference not set to an instance of an object
Projectile.MakeCollectible () (at Assets/Player/Projectiles/Projectile.cs:449)
Projectile.Land () (at Assets/Player/Projectiles/Projectile.cs:408)
Projectile.OnTriggerEnter2D (UnityEngine.Collider2D collision) (at Assets/Player/Projectiles/Projectile.cs:180)

NullReferenceException: Object reference not set to an instance of an object
ProjectileSegment.OnTriggerEnter2D (UnityEngine.Collider2D collision) (at Assets/Player/Projectiles/ProjectileSegment.cs:43)